let places = ["Paris", "Sydney", "New York", "Tokyo", "Cairo"];
console.log("Original order: ", places);
places.sort();
console.log("Alphabetical order: ", places);
console.log("Original order: ", places);
places.sort().reverse();
console.log("Reverse alphabetical order: ", places);
console.log("Original order: ", places);
places.reverse();
console.log("Reversed order: ", places);
places.reverse();
console.log("Original order: ", places);
places.sort();
console.log("Alphabetical order: ", places);
places.reverse();
console.log("Reverse alphabetical order: ", places);
